framework:
    secret: '%env(APP_SECRET)%'
    annotations: true
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    #session:
    #    handler_id: null
    #    cookie_secure: auto
    #    cookie_samesite: lax

    session:
        #handler_id: session.handler.native_file
        # For Symfony 5.4/6.4 this is fine:
        #handler_id: null
        #save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        # 2 Days lifetime (172800 seconds)
        #cookie_lifetime: 31536000
        #cookie_secure: 'auto'
        #cookie_samesite: 'lax'
        enabled: true
        handler_id: null
        storage_factory_id: session.storage.factory.native
        cookie_lifetime: 31536000
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

#The Templating Component itself is not deprecated, the integration with the FrameworkBundle is deprecated. So removing that option is enough.
#    templating:
#        engines: ['php']
#        engines: ['twig', 'php']
