reset_my_password_mail:
  path:     resetpassword/sendmail
  controller: App\Controller\ResetPassController::sendMailAction


my_forgot_password_request:
  path:     resetpassword/request
  controller: App\Controller\ResetPassController::requestAction

app_check_email:
  path:     resetpassword/checkemail
  controller: App\Controller\ResetPassController::checkEmailAction

